version: '3'
services:
  ipc:
    image: redis
    ports: 
      - "6379:6379"
  reverse_proxy:
        build: ./src/reverse.proxy
        ports:
            - "5002:80"
  thermal_api:
        build: ./src/thermal_api
        environment:
          - REDIS_HOST=ipc
        depends_on:
          ipc